SELECT
    shipment_id,
    order_id,
    carrier_id,
    carrier_name,
    service_tier,
    origin_warehouse_id,
    origin_city,
    origin_country,
    destination_warehouse_id,
    destination_city,
    destination_country,
    CAST(shipment_created_ts AS TIMESTAMP) AS shipment_created_ts,
    CAST(shipment_created_ts AS DATE) AS shipment_date,
    expected_delivery_ts,
    delivery_ts,
    distance_km,
    cross_border,
    network_load_factor,
    sla_hours,
    actual_transit_hours,
    delay_hours,
    delay_probability,
    delayed_flag,
    sla_met,
    no_scan_flag,
    damaged_flag,
    lost_flag,
    shipment_status

FROM {{ source('bronze', 'shipments') }}
